<?php
   $googleTagManagerStatus = Mage::getStoreConfig('clearsale_fingerprint_settings/settings/config_google_tag_manager', Mage::app()->getStore());
   $sessionID = Mage::getSingleton("core/session")->getEncryptedSessionId();
    $appName = Mage::getStoreConfig('clearsale_fingerprint_settings/settings/app_name', Mage::app()->getStore());

    if($googleTagManagerStatus == true) {
        echo '<input type="hidden" id="magento_sessionID" value="' . $sessionID . '">';
        ?>
        <script>
            jQuery(document).ready(function  () {
                (function (a, b, c, d, e, f, g) {
                a['CsdpObject'] = e; a[e] = a[e] || function () {
                (a[e].q = a[e].q || []).push(arguments)
                }, a[e].l = 1 * new Date(); f = b.createElement(c),
                g = b.getElementsByTagName(c)[0]; f.async = 1; f.src = d; g.parentNode.insertBefore(f, g)
                })(window, document, 'script', '//device.clearsale.com.br/p/fp.js', 'csdp');
                csdp('app', '<?php echo $appName ?>');
                csdp('inputsessionid', "magento_sessionID");
            })
        </script>
        <?php
    } else {
        ?>
        <script>
            (function (a, b, c, d, e, f, g) {
            a['CsdpObject'] = e; a[e] = a[e] || function () {
            (a[e].q = a[e].q || []).push(arguments)
            }, a[e].l = 1 * new Date(); f = b.createElement(c),
            g = b.getElementsByTagName(c)[0]; f.async = 1; f.src = d; g.parentNode.insertBefore(f, g)
            })(window, document, 'script', '//device.clearsale.com.br/p/fp.js', 'csdp');
            csdp('app', '<?php echo $appName ?>');
            csdp('sessionid', '<?php echo $sessionID ?>');
        </script>
        <?php
    }