<?php echo $this->getChildHtml('bottomContainer'); ?>

<div class="footer">
	<div class="linha">
		<div class="conteudo">
      <ul class="footer_coluna">
				<li><a href="/loja/index.php/produtos.html">Loja</a></li>
        <li><a href="/loja/sobre">Sobre</a></li>
				<li><a href="/loja/contato">Contato</a></li>
        <li><a href="/loja/suporte-tecnico">Suporte técnico</a></li>
      </ul>
      <ul class="footer_coluna">
				<li><a href="/blog">Blog</a></li>
				<li><a href="https://www.linkedin.com/company/e-motors-mobility-solutions/" target="_blank">Linkedin</a></li>
        <li><a href="https://www.facebook.com/emotorsbr/?epa=SEARCH_BOX" target="_blank">Facebook</a></li>
        <li><a href="https://www.instagram.com/emotors_br/?hl=pt-br" target="_blank">Instagram</a></li>
      </ul>
			<ul class="footer_coluna">
				<li>E-mails:</li>
				<li>fabio@emotors.mobi</li>
				<li>tiago@emotors.mobi</li>
				<li>bruno@emotors.mobi</li>
			</ul>
      <ul class="footer_coluna">
        <li>
					<div class="botao_principal--medio">
						<a href="http://materiais.e-motors.mobi/revendedor" target="_blank">Seja revendedor</a>
					</div>
				</li>
      </ul>
		</div>
	</div>
</div>

<?php $athleteHelper = Mage::helper('athlete'); ?>

<?php if (!$athleteHelper->getCfg('footer/copyright_line')): ?>

<div class="copyright">
	<p>E-Motors. Site desenvolvido por <a href="https://www.lionsdigital.com.br/" target="_blank" style="color:#fff;">Lions Digital</a></p>
</div>

<?php endif; ?>
